### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by RobinFrcd** [ubiquiti-community/py-unifi#3]
Hi,
I just installed the package with `pip install git+https://github.com/ubiquiti-community/py-unifi.git`.
But it just doesn't work, can't even import it.

```python
>>> import unifi_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.11/site-packages/unifi_client/__init__.py", line 20, in <module>
    from unifi_client.account_api import AccountApi
ModuleNotFoundError: No module named 'unifi_client.account_api'
```

Is this repo supposed to work ?

Thanks !

**Comment by Nathan1258** [comment]
Hi sorry this is late but I fixed it in this PR: https://github.com/ubiquiti-community/py-unifi/pull/5
